### ISSUE TITLE
«Argument 1 passed to Df\Sentry\Trace::get_frame_context() must be of the type array, null given, called in vendor/mage2pro/core/Sentry/Trace.php on line 38 and defined in vendor/mage2pro/core/Sentry/Trace.php:156»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [mage2pro/core#103]
[https://mage2.pro/t/6160](https://mage2.pro/t/6160)

Stack trace:
```
#0 vendor/mage2pro/core/Sentry/Trace.php(38): Df\Sentry\Trace::get_frame_context(NULL)
#1 vendor/mage2pro/core/Sentry/Client.php(103): Df\Sentry\Trace::info(Array)
#2 vendor/mage2pro/core/Sentry/lib/main.php(82): Df\Sentry\Client->captureException(Object(Df\Core\Exception), Array)
#3 vendor/mage2pro/core/Payment/W/Action.php(63): df_sentry(‘Dfe_IPay88’, Object(Df\Core\Exception))
#4 vendor/magento/framework/Interception/Interceptor.php(58): Df\Payment\W\Action->execute()
#5 vendor/magento/framework/Interception/Interceptor.php(138): Df\Payment\W\Action\Interceptor
File: vendor/mage2pro/core/Sentry/Trace.php
Line: 156
```

**Comment by dmitry-fedyuk** [comment]
Fixed in [6.7.0](https://github.com/mage2pro/core/releases/tag/6.7.0).
