### ISSUE TITLE
«Class 'Magento\SampleData\Model\Dependency' not found in vendor/mage2pro/core/SampleData/Model/Dependency.php:10»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/core#225]
I fixed the previous error by checking the result of dfa function if null or not
but after that i continued to execute `bin/magento setup:di:compile` and get this error:

`Fatal error: Uncaught Error: Class 'Magento\SampleData\Model\Dependency' not found in /home/lelasinfo/public_html/vendor/mage2pro/core/SampleData/Model/Dependency.php:10
Stack trace:
#0 /home/lelasinfo/public_html/vendor/composer/ClassLoader.php(571): include()
mage2pro/yandex-kassa#1 /home/lelasinfo/public_html/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/lelasinfo...')
mage2pro/yandex-kassa#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Df\\SampleData\\M...')
mage2pro/yandex-kassa#3 [internal function]: spl_autoload_call('Df\\SampleData\\M...')
mage2pro/yandex-kassa#4 /home/lelasinfo/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Df\\SampleData\\M...')
mage2pro/core#226 /home/lelasinfo/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Df\\SampleData\\M...', '/home/lelasinfo...')
#6 /home/lelasinfo/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesSca in /home/lelasinfo/public_html/vendor/mage2pro/core/SampleData/Model/Dependency.php on line 10`

_Originally posted by @AlaaL in https://github.com/mage2pro/core/issues/226

**Comment by dmitrii-fediuk** [comment]
The class `Magento\SampleData\Model\Dependency` exists in all Magento 2 versions:
- **2.4.7-beta1**: https://github.com/magento/magento2/blob/2.4.7-beta1/app/code/Magento/SampleData/Model/Dependency.php
- **2.0.0**: https://github.com/magento/magento2/blob/2.0.0/app/code/Magento/SampleData/Model/Dependency.php
