### ISSUE TITLE
«Trying to access array offset on value of type null in vendor/composer/composer/src/Composer/InstalledVersions.php on line 198»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/core#243]
Related to https://github.com/mage2pro/core/issues/229

**Comment by dmitrii-fediuk** [comment]
```
#0 vendor\composer\composer\src\Composer\InstalledVersions.php(198): Magento\Framework\App\ErrorHandler->handler(8, 'Trying to acces...', 'C:\\work\\clients...', 198, Array) 
#1 vendor\mage2pro\core\Core\lib\state.php(81): Composer\InstalledVersions::getRootPackage() 
#2 vendor\mage2pro\core\Core\lib\cache\dfc.php(167): {closure}() 
#3 vendor\mage2pro\core\Core\lib\state.php(82): dfcf(Object(Closure)) 
#4 vendor\mage2pro\core\Qa\lib\context.php(9): df_magento_version() 
#5 vendor\mage2pro\core\Qa\lib\log.php(81): df_context() 
#6 vendor\mage2pro\core\Qa\lib\log.php(41): df_log_l('Df\\Intl\\Js', Object(Exception), Array, '___callPlugins') 
#7 vendor\mage2pro\core\Framework\Plugin\AppInterface.php(55): df_log_e(Object(Exception)) 
```
