### ISSUE TITLE
«Area code not set: Area code must be set before starting a session» in `lib/internal/Magento/Framework/App/State.php:149` on `static/adminhtml/Magento/backend/en_US/moment.min.js.map`

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/core#316]
```
mage2pro/core: 10.2.3
Magento: 2.4-develop
PHP: 8.1.11
URL: https://localhost.com:2190/static/adminhtml/Magento/backend/en_US/moment.min.js.map
Time: 2023-08-04 23:20:20
IP Address: 158.181.235.66
Request Method: GET
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
File: lib/internal/Magento/Framework/Session/SessionManager.php
Line: 171
************************************
[E_ERROR] Uncaught Magento\Framework\Exception\LocalizedException: Area code is not set in lib/internal/Magento/Framework/App/State.php:149
Stack trace:
#0 generated/code/Magento/Framework/App/State/Interceptor.php(50): Magento\Framework\App\State->getAreaCode()
#1 lib/internal/Magento/Framework/Session/SessionManager.php(169): Magento\Framework\App\State\Interceptor->getAreaCode()
#2 lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\Session\SessionManager->start()
#3 lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Backend\Model\Auth\Session\Interceptor->___callParent('start', Array)
#4 lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Backend\Model\Auth\Session\Interceptor->Magento\Framework\Interception\{closure}()
#5 generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(149): Magento\Backend\Model\Auth\Session\Interceptor->___callPlugins('start', Array, Array)
#6 lib/internal/Magento/Framework/Session/SessionManager.php(124): Magento\Backend\Model\Auth\Session\Interceptor->start()
#7 app/code/Magento/Backend/Model/Auth/Session.php(105): Magento\Framework\Session\SessionManager->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State\Interceptor))
#8 generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(14): Magento\Backend\Model\Auth\Session->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State\Interceptor), Object(Magento\Framework\Acl\Builder\Proxy), Object(Magento\Backend\Model\Url), Object(Magento\Backend\App\Config), NULL)
#9 lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Backend\Model\Auth\Session\Interceptor->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State\Interceptor), Object(Magento\Framework\Acl\Builder\Proxy), Object(Magento\Backend\Model\Url), Object(Magento\Backend\App\Config), NULL)
#10 lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Backend...', Array)
#11 lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...')
#12 vendor/mage2pro/core/Core/lib/object/om.php(83): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Backend...')
#13 vendor/mage2pro/core/Core/lib/cache/dfc.php(167): {closure}('Magento\\Backend...')
#14 vendor/mage2pro/core/Core/lib/object/om.php(83): dfcf(Object(Closure), Array)
#15 vendor/mage2pro/core/Backend/lib/main.php(19): df_o('Magento\\Backend...')
#16 vendor/mage2pro/core/Backend/lib/main.php(31): df_backend_session()
#17 vendor/mage2pro/core/Sentry/lib/main.php(171): df_backend_user()
#18 vendor/mage2pro/core/Core/lib/cache/dfc.php(167): {closure}('Df_Core')
#19 vendor/mage2pro/core/Sentry/lib/main.php(186): dfcf(Object(Closure), Array)
#20 vendor/mage2pro/core/Sentry/lib/main.php(184): df_sentry_m('Df_Core')
#21 vendor/mage2pro/core/Core/lib/cache/dfc.php(167): {closure}('Df_Framework')
#22 vendor/mage2pro/core/Sentry/lib/main.php(186): dfcf(Object(Closure), Array)
#23 vendor/mage2pro/core/Sentry/lib/main.php(77): df_sentry_m('Df_Framework')
#24 vendor/mage2pro/core/Qa/lib/log.php(37): df_sentry('Df_Framework', Object(InvalidArgumentException), Array)
#25 vendor/mage2pro/core/Framework/Plugin/App/Response/HttpInterface.php(17): df_log(Object(InvalidArgumentException))
#26 lib/internal/Magento/Framework/Interception/Interceptor.php(121): Df\Framework\Plugin\App\Response\HttpInterface->beforeSetBody(Object(Magento\Framework\HTTP\PhpEnvironment\Response\Interceptor), Object(InvalidArgumentException))
#27 lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\HTTP\PhpEnvironment\Response\Interceptor->Magento\Framework\Interception\{closure}(Object(InvalidArgumentException))
#28 generated/code/Magento/Framework/HTTP/PhpEnvironment/Response/Interceptor.php(49): Magento\Framework\HTTP\PhpEnvironment\Response\Interceptor->___callPlugins('setBody', Array, Array)
#29 lib/internal/Magento/Framework/App/Bootstrap.php(438): Magento\Framework\HTTP\PhpEnvironment\Response\Interceptor->setBody(Object(InvalidArgumentException))
#30 lib/internal/Magento/Framework/App/Bootstrap.php(275): Magento\Framework\App\Bootstrap->terminate(Object(InvalidArgumentException))
#31 pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource\Interceptor))
#32 {main}

Next Magento\Framework\Exception\SessionException: Area code not set: Area code must be set before starting a session. in lib/internal/Magento/Framework/Session/SessionManager.php:171
Stack trace:
#0 lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\Session\SessionManager->start()
#1 lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Backend\Model\Auth\Session\Interceptor->___callParent('start', Array)
#2 lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Backend\Model\Auth\Session\Interceptor->Magento\Framework\Interception\{closure}()
#3 generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(149): Magento\Backend\Model\Auth\Session\Interceptor->___callPlugins('start', Array, Array)
#4 lib/internal/Magento/Framework/Session/SessionManager.php(124): Magento\Backend\Model\Auth\Session\Interceptor->start()
#5 app/code/Magento/Backend/Model/Auth/Session.php(105): Magento\Framework\Session\SessionManager->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State\Interceptor))
#6 generated/code/Magento/Backend/Model/Auth/Session/Interceptor.php(14): Magento\Backend\Model\Auth\Session->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State\Interceptor), Object(Magento\Framework\Acl\Builder\Proxy), Object(Magento\Backend\Model\Url), Object(Magento\Backend\App\Config), NULL)
#7 lib/internal/Magento/Framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Backend\Model\Auth\Session\Interceptor->__construct(Object(Magento\Framework\App\Request\Http), Object(Magento\Framework\Session\SidResolver\Proxy), Object(Magento\Framework\Session\Config), Object(Magento\Framework\Session\SaveHandler), Object(Magento\Framework\Session\Validator), Object(Magento\Framework\Session\Storage), Object(Magento\Framework\Stdlib\Cookie\PhpCookieManager), Object(Magento\Framework\Stdlib\Cookie\CookieMetadataFactory), Object(Magento\Framework\App\State\Interceptor), Object(Magento\Framework\Acl\Builder\Proxy), Object(Magento\Backend\Model\Url), Object(Magento\Backend\App\Config), NULL)
#8 lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Backend...', Array)
#9 lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(73): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Backend...')
#10 vendor/mage2pro/core/Core/lib/object/om.php(83): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Backend...')
#11 vendor/mage2pro/core/Core/lib/cache/dfc.php(167): {closure}('Magento\\Backend...')
#12 vendor/mage2pro/core/Core/lib/object/om.php(83): dfcf(Object(Closure), Array)
#13 vendor/mage2pro/core/Backend/lib/main.php(19): df_o('Magento\\Backend...')
#14 vendor/mage2pro/core/Backend/lib/main.php(31): df_backend_session()
#15 vendor/mage2pro/core/Sentry/lib/main.php(171): df_backend_user()
#16 vendor/mage2pro/core/Core/lib/cache/dfc.php(167): {closure}('Df_Core')
#17 vendor/mage2pro/core/Sentry/lib/main.php(186): dfcf(Object(Closure), Array)
#18 vendor/mage2pro/core/Sentry/lib/main.php(184): df_sentry_m('Df_Core')
#19 vendor/mage2pro/core/Core/lib/cache/dfc.php(167): {closure}('Df_Framework')
#20 vendor/mage2pro/core/Sentry/lib/main.php(186): dfcf(Object(Closure), Array)
#21 vendor/mage2pro/core/Sentry/lib/main.php(77): df_sentry_m('Df_Framework')
#22 vendor/mage2pro/core/Qa/lib/log.php(37): df_sentry('Df_Framework', Object(InvalidArgumentException), Array)
#23 vendor/mage2pro/core/Framework/Plugin/App/Response/HttpInterface.php(17): df_log(Object(InvalidArgumentException))
#24 lib/internal/Magento/Framework/Interception/Interceptor.php(121): Df\Framework\Plugin\App\Response\HttpInterface->beforeSetBody(Object(Magento\Framework\HTTP\PhpEnvironment\Response\Interceptor), Object(InvalidArgumentException))
#25 lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\HTTP\PhpEnvironment\Response\Interceptor->Magento\Framework\Interception\{closure}(Object(InvalidArgumentException))
#26 generated/code/Magento/Framework/HTTP/PhpEnvironment/Response/Interceptor.php(49): Magento\Framework\HTTP\PhpEnvironment\Response\Interceptor->___callPlugins('setBody', Array, Array)
#27 lib/internal/Magento/Framework/App/Bootstrap.php(438): Magento\Framework\HTTP\PhpEnvironment\Response\Interceptor->setBody(Object(InvalidArgumentException))
#28 lib/internal/Magento/Framework/App/Bootstrap.php(275): Magento\Framework\App\Bootstrap->terminate(Object(InvalidArgumentException))
#29 pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource\Interceptor))
#30 {main}
  thrown
```

**Comment by dmitrii-fediuk** [comment]
It seems to be related to https://github.com/mage2pro/core/issues/309
