### ISSUE TITLE
«Unable to detect a module for the file: `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml`»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [mage2pro/core#358]
```
mage2pro/core: 10.7.1
Magento: 2.4.4
PHP: 7.4.9
URL: https://localhost.com:2255/ready-to-assemble-cabinets/steam-white-shaker.html
Time: 2024-03-10 15:48:43
IP Address: 158.181.235.66
Request Method: GET
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
File: vendor/mage2pro/core/Qa/lib/validation/error.php
Line: 203
************************************
[E_ERROR] Uncaught Df\Core\Exception: Unable to detect the module for the file: `app/design/frontend/Cabinetsbay/cabinetsbay_default/Magento_Catalog/templates/category/header.phtml` in vendor/mage2pro/core/Qa/lib/validation/error.php:203
Stack trace:
#0 vendor/mage2pro/core/Qa/lib/validation/error.php(155): df_error_create('Unable to detec...')
#1 vendor/mage2pro/core/Qa/lib/validation/assert/eq.php(95): df_error('Unable to detec...')
#2 vendor/mage2pro/core/Framework/lib/module/fs/name.php(97): df_assert_ne('app/design/fron...', 'app/design/fron...', 'Unable to detec...')
#3 vendor/mage2pro/core/Core/lib/caller/other.php(116): df_module_name_by_path('app/design/fron...')
#4 vendor/mage2pro/core/Qa/lib/log.php(36): df_caller
```

**Comment by dmitrii-fediuk** [comment]
Solved by https://github.com/mage2pro/core/issues/359
