### ISSUE TITLE
AlphaCommerceHub with POLi Payments: «Invalid result class: Df\Framework\W\Result\Text»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [mage2pro/core#58]
```
1 exception(s):
Exception #0 (Df\Core\Exception): Invalid result class: Df\Framework\W\Result\Text.

Exception #0 (Df\Core\Exception): Invalid result class: Df\Framework\W\Result\Text.
#0 vendor/mage2pro/core/Core/lib/validation.php(529): df_error_create('Invalid result ...', 'Df\\Framework\\W\\...')
#1 vendor/mage2pro/core/Payment/W/Action.php(102): df_error('Invalid result ...', 'Df\\Framework\\W\\...')
#2 lib/internal/Magento/Framework/Interception/Interceptor.php(58): Df\Payment\W\Action->execute()
#3 lib/internal/Magento/Framework/Interception/Interceptor.php(138): Df\Payment\W\Action\Interceptor->___callParent('execute', Array)
#4 lib/internal/Magento/Framework/Interception/Interceptor.php(153): Df\Payment\W\Action\Interceptor->Magento\Framework\Interception\{closure}()
#5 generated/code/Df/Payment/W/Action/Interceptor.php(26): Df\Payment\W\Action\Interceptor->___callPlugins('execute', Array, Array)
#6 lib/internal/Magento/Framework/App/Action/Action.php(107): Df\Payment\W\Action\Interceptor->execute()
#7 lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#8 lib/internal/Magento/Framework/Interception/Interceptor.php(138): Df\Payment\W\Action\Interceptor->___callParent('dispatch', Array)
#9 lib/internal/Magento/Framework/Interception/Interceptor.php(153): Df\Payment\W\Action\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 generated/code/Df/Payment/W/Action/Interceptor.php(39): Df\Payment\W\Action\Interceptor->___callPlugins('dispatch', Array, Array)
#11 lib/internal/Magento/Framework/App/FrontController.php(55): Df\Payment\W\Action\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#12 lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#13 lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#14 app/code/Magento/Store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#16 app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#17 lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#18 lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#19 generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#20 lib/internal/Magento/Framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#21 lib/internal/Magento/Framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#22 index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#23 {main}
```

**Comment by dmitry-fedyuk** [comment]
Fixed in [3.3.31](https://github.com/mage2pro/core/releases/tag/3.3.31).
